version: '3'

services:
  namenode:
    image: bde2020/hadoop-namenode:${HADOOP_VERSION}
    networks:
      - ${HDFS_NETWORK}
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=${HDFS_NETWORK}
    env_file:
      - ./hadoop.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  datanode:
    image: bde2020/hadoop-datanode:${HADOOP_VERSION}
    networks:
      - ${HDFS_NETWORK}
    container_name: datanode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    depends_on:
      - namenode
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:${HADOOP_VERSION}
    networks:
      - ${HDFS_NETWORK}
    container_name: resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
      - datanode
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      disable: true

  nodemanager:
    image: bde2020/hadoop-nodemanager:${HADOOP_VERSION}
    networks:
      - ${HDFS_NETWORK}
    container_name: nodemanager
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
      - datanode
      - resourcemanager
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  historyserver:
    image: bde2020/hadoop-historyserver:${HADOOP_VERSION}
    networks:
      - ${HDFS_NETWORK}
    container_name: historyserver
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
      - datanode
      - resourcemanager
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  hbase:
    image: bde2020/hbase-standalone:${HBASE_VERSION}
    networks:
      - ${HDFS_NETWORK}
    container_name: hbase
    volumes:
      - hbase_data:/hbase-data
      - hbase_zookeeper_data:/zookeeper-data
    ports:
      - 16000:16000
      - 16010:16010
      - 16020:16020
      - 16030:16030
      - 2888:2888
      - 3888:3888
      - 2181:2181
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
      - datanode
      - resourcemanager
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  postgresql:
    image: bde2020/hive-metastore-postgresql:${POSTGRESQL_VERSION}
    networks:
      - ${HDFS_NETWORK}
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      PGPASSWORD: postgres
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  hive-metastore:
    image: bde2020/hive:${HIVE_VERSION}
    networks:
      - ${HDFS_NETWORK}
    container_name: hive-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 postgresql:5432"
    ports:
      - "9083:9083"
    depends_on:
      - namenode
      - datanode
      - resourcemanager
      - postgresql
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  hive-server:
    image: bde2020/hive:${HIVE_VERSION}
    networks:
      - ${HDFS_NETWORK}
    container_name: hive-server
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 hive-metastore:9083"
    ports:
      - "10000:10000"
    depends_on:
      - namenode
      - datanode
      - resourcemanager
      - hive-metastore
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  presto-coordinator:
    image: datagrip/prestodb:${PRESTODB_VERSION}
    networks:
      - ${HDFS_NETWORK}
    container_name: hive-presto
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  ${HDFS_NETWORK}:

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
  hbase_data:
  hbase_zookeeper_data:
